// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bookmark_collections.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package BookmarkCollection;

@kotlin.jvm.JvmName("-initializedeleteBookmarkCollectionResponse")
public inline fun deleteBookmarkCollectionResponse(block: BookmarkCollection.DeleteBookmarkCollectionResponseKt.Dsl.() -> kotlin.Unit): BookmarkCollection.BookmarkCollections.DeleteBookmarkCollectionResponse =
  BookmarkCollection.DeleteBookmarkCollectionResponseKt.Dsl._create(BookmarkCollection.BookmarkCollections.DeleteBookmarkCollectionResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `BookmarkCollection.DeleteBookmarkCollectionResponse`
 */
public object DeleteBookmarkCollectionResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: BookmarkCollection.BookmarkCollections.DeleteBookmarkCollectionResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: BookmarkCollection.BookmarkCollections.DeleteBookmarkCollectionResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): BookmarkCollection.BookmarkCollections.DeleteBookmarkCollectionResponse = _builder.build()

    /**
     * `string BookmarkCollection_id = 1;`
     */
    public var bookmarkCollectionId: kotlin.String
      @JvmName("getBookmarkCollectionId")
      get() = _builder.bookmarkCollectionId
      @JvmName("setBookmarkCollectionId")
      set(value) {
        _builder.bookmarkCollectionId = value
      }
    /**
     * `string BookmarkCollection_id = 1;`
     */
    public fun clearBookmarkCollectionId() {
      _builder.clearBookmarkCollectionId()
    }

    /**
     * `string message = 2;`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.message
      @JvmName("setMessage")
      set(value) {
        _builder.message = value
      }
    /**
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun BookmarkCollection.BookmarkCollections.DeleteBookmarkCollectionResponse.copy(block: `BookmarkCollection`.DeleteBookmarkCollectionResponseKt.Dsl.() -> kotlin.Unit): BookmarkCollection.BookmarkCollections.DeleteBookmarkCollectionResponse =
  `BookmarkCollection`.DeleteBookmarkCollectionResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

