// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bookmark_collections.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package BookmarkCollection;

@kotlin.jvm.JvmName("-initializegetBookmarkCollectionResponse")
public inline fun getBookmarkCollectionResponse(block: BookmarkCollection.GetBookmarkCollectionResponseKt.Dsl.() -> kotlin.Unit): BookmarkCollection.BookmarkCollections.GetBookmarkCollectionResponse =
  BookmarkCollection.GetBookmarkCollectionResponseKt.Dsl._create(BookmarkCollection.BookmarkCollections.GetBookmarkCollectionResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `BookmarkCollection.GetBookmarkCollectionResponse`
 */
public object GetBookmarkCollectionResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: BookmarkCollection.BookmarkCollections.GetBookmarkCollectionResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: BookmarkCollection.BookmarkCollections.GetBookmarkCollectionResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): BookmarkCollection.BookmarkCollections.GetBookmarkCollectionResponse = _builder.build()

    /**
     * `string BookmarkCollection_id = 1;`
     */
    public var bookmarkCollectionId: kotlin.String
      @JvmName("getBookmarkCollectionId")
      get() = _builder.bookmarkCollectionId
      @JvmName("setBookmarkCollectionId")
      set(value) {
        _builder.bookmarkCollectionId = value
      }
    /**
     * `string BookmarkCollection_id = 1;`
     */
    public fun clearBookmarkCollectionId() {
      _builder.clearBookmarkCollectionId()
    }

    /**
     * `string name = 2;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string description = 3;`
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.description
      @JvmName("setDescription")
      set(value) {
        _builder.description = value
      }
    /**
     * `string description = 3;`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * `string created_at = 4;`
     */
    public var createdAt: kotlin.String
      @JvmName("getCreatedAt")
      get() = _builder.createdAt
      @JvmName("setCreatedAt")
      set(value) {
        _builder.createdAt = value
      }
    /**
     * `string created_at = 4;`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }

    /**
     * `string updated_at = 5;`
     */
    public var updatedAt: kotlin.String
      @JvmName("getUpdatedAt")
      get() = _builder.updatedAt
      @JvmName("setUpdatedAt")
      set(value) {
        _builder.updatedAt = value
      }
    /**
     * `string updated_at = 5;`
     */
    public fun clearUpdatedAt() {
      _builder.clearUpdatedAt()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EntriesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .BookmarkCollection.BookmarkCollectionEntries entries = 7;`
     */
     public val entries: com.google.protobuf.kotlin.DslList<BookmarkCollection.BookmarkCollections.BookmarkCollectionEntries, EntriesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.entriesList
      )
    /**
     * `repeated .BookmarkCollection.BookmarkCollectionEntries entries = 7;`
     * @param value The entries to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEntries")
    public fun com.google.protobuf.kotlin.DslList<BookmarkCollection.BookmarkCollections.BookmarkCollectionEntries, EntriesProxy>.add(value: BookmarkCollection.BookmarkCollections.BookmarkCollectionEntries) {
      _builder.addEntries(value)
    }
    /**
     * `repeated .BookmarkCollection.BookmarkCollectionEntries entries = 7;`
     * @param value The entries to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEntries")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<BookmarkCollection.BookmarkCollections.BookmarkCollectionEntries, EntriesProxy>.plusAssign(value: BookmarkCollection.BookmarkCollections.BookmarkCollectionEntries) {
      add(value)
    }
    /**
     * `repeated .BookmarkCollection.BookmarkCollectionEntries entries = 7;`
     * @param values The entries to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEntries")
    public fun com.google.protobuf.kotlin.DslList<BookmarkCollection.BookmarkCollections.BookmarkCollectionEntries, EntriesProxy>.addAll(values: kotlin.collections.Iterable<BookmarkCollection.BookmarkCollections.BookmarkCollectionEntries>) {
      _builder.addAllEntries(values)
    }
    /**
     * `repeated .BookmarkCollection.BookmarkCollectionEntries entries = 7;`
     * @param values The entries to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEntries")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<BookmarkCollection.BookmarkCollections.BookmarkCollectionEntries, EntriesProxy>.plusAssign(values: kotlin.collections.Iterable<BookmarkCollection.BookmarkCollections.BookmarkCollectionEntries>) {
      addAll(values)
    }
    /**
     * `repeated .BookmarkCollection.BookmarkCollectionEntries entries = 7;`
     * @param index The index to set the value at.
     * @param value The entries to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEntries")
    public operator fun com.google.protobuf.kotlin.DslList<BookmarkCollection.BookmarkCollections.BookmarkCollectionEntries, EntriesProxy>.set(index: kotlin.Int, value: BookmarkCollection.BookmarkCollections.BookmarkCollectionEntries) {
      _builder.setEntries(index, value)
    }
    /**
     * `repeated .BookmarkCollection.BookmarkCollectionEntries entries = 7;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEntries")
    public fun com.google.protobuf.kotlin.DslList<BookmarkCollection.BookmarkCollections.BookmarkCollectionEntries, EntriesProxy>.clear() {
      _builder.clearEntries()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun BookmarkCollection.BookmarkCollections.GetBookmarkCollectionResponse.copy(block: `BookmarkCollection`.GetBookmarkCollectionResponseKt.Dsl.() -> kotlin.Unit): BookmarkCollection.BookmarkCollections.GetBookmarkCollectionResponse =
  `BookmarkCollection`.GetBookmarkCollectionResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

