// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bookmark_collections.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package BookmarkCollection;

@kotlin.jvm.JvmName("-initializelistBookmarkCollectionsRequest")
public inline fun listBookmarkCollectionsRequest(block: BookmarkCollection.ListBookmarkCollectionsRequestKt.Dsl.() -> kotlin.Unit): BookmarkCollection.BookmarkCollections.ListBookmarkCollectionsRequest =
  BookmarkCollection.ListBookmarkCollectionsRequestKt.Dsl._create(BookmarkCollection.BookmarkCollections.ListBookmarkCollectionsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `BookmarkCollection.ListBookmarkCollectionsRequest`
 */
public object ListBookmarkCollectionsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: BookmarkCollection.BookmarkCollections.ListBookmarkCollectionsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: BookmarkCollection.BookmarkCollections.ListBookmarkCollectionsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): BookmarkCollection.BookmarkCollections.ListBookmarkCollectionsRequest = _builder.build()

    /**
     * `uint32 page = 1;`
     */
    public var page: kotlin.Int
      @JvmName("getPage")
      get() = _builder.page
      @JvmName("setPage")
      set(value) {
        _builder.page = value
      }
    /**
     * `uint32 page = 1;`
     */
    public fun clearPage() {
      _builder.clearPage()
    }

    /**
     * `uint32 page_size = 2;`
     */
    public var pageSize: kotlin.Int
      @JvmName("getPageSize")
      get() = _builder.pageSize
      @JvmName("setPageSize")
      set(value) {
        _builder.pageSize = value
      }
    /**
     * `uint32 page_size = 2;`
     */
    public fun clearPageSize() {
      _builder.clearPageSize()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun BookmarkCollection.BookmarkCollections.ListBookmarkCollectionsRequest.copy(block: `BookmarkCollection`.ListBookmarkCollectionsRequestKt.Dsl.() -> kotlin.Unit): BookmarkCollection.BookmarkCollections.ListBookmarkCollectionsRequest =
  `BookmarkCollection`.ListBookmarkCollectionsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

