// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bookmark_collections.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package BookmarkCollection;

@kotlin.jvm.JvmName("-initializenewBookmarkCollectionResponse")
public inline fun newBookmarkCollectionResponse(block: BookmarkCollection.NewBookmarkCollectionResponseKt.Dsl.() -> kotlin.Unit): BookmarkCollection.BookmarkCollections.NewBookmarkCollectionResponse =
  BookmarkCollection.NewBookmarkCollectionResponseKt.Dsl._create(BookmarkCollection.BookmarkCollections.NewBookmarkCollectionResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `BookmarkCollection.NewBookmarkCollectionResponse`
 */
public object NewBookmarkCollectionResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: BookmarkCollection.BookmarkCollections.NewBookmarkCollectionResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: BookmarkCollection.BookmarkCollections.NewBookmarkCollectionResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): BookmarkCollection.BookmarkCollections.NewBookmarkCollectionResponse = _builder.build()

    /**
     * `string BookmarkCollection_id = 1;`
     */
    public var bookmarkCollectionId: kotlin.String
      @JvmName("getBookmarkCollectionId")
      get() = _builder.bookmarkCollectionId
      @JvmName("setBookmarkCollectionId")
      set(value) {
        _builder.bookmarkCollectionId = value
      }
    /**
     * `string BookmarkCollection_id = 1;`
     */
    public fun clearBookmarkCollectionId() {
      _builder.clearBookmarkCollectionId()
    }

    /**
     * `string name = 3;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `string name = 3;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string description = 4;`
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.description
      @JvmName("setDescription")
      set(value) {
        _builder.description = value
      }
    /**
     * `string description = 4;`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * `string created_at = 5;`
     */
    public var createdAt: kotlin.String
      @JvmName("getCreatedAt")
      get() = _builder.createdAt
      @JvmName("setCreatedAt")
      set(value) {
        _builder.createdAt = value
      }
    /**
     * `string created_at = 5;`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }

    /**
     * `string updated_at = 6;`
     */
    public var updatedAt: kotlin.String
      @JvmName("getUpdatedAt")
      get() = _builder.updatedAt
      @JvmName("setUpdatedAt")
      set(value) {
        _builder.updatedAt = value
      }
    /**
     * `string updated_at = 6;`
     */
    public fun clearUpdatedAt() {
      _builder.clearUpdatedAt()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun BookmarkCollection.BookmarkCollections.NewBookmarkCollectionResponse.copy(block: `BookmarkCollection`.NewBookmarkCollectionResponseKt.Dsl.() -> kotlin.Unit): BookmarkCollection.BookmarkCollections.NewBookmarkCollectionResponse =
  `BookmarkCollection`.NewBookmarkCollectionResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

