// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bookmark_collection_entries.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bookmark_collections_entries;

@kotlin.jvm.JvmName("-initializegetBookmarkCollectionsEntryResponse")
public inline fun getBookmarkCollectionsEntryResponse(block: bookmark_collections_entries.GetBookmarkCollectionsEntryResponseKt.Dsl.() -> kotlin.Unit): bookmark_collections_entries.BookmarkCollectionEntries.GetBookmarkCollectionsEntryResponse =
  bookmark_collections_entries.GetBookmarkCollectionsEntryResponseKt.Dsl._create(bookmark_collections_entries.BookmarkCollectionEntries.GetBookmarkCollectionsEntryResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `bookmark_collections_entries.GetBookmarkCollectionsEntryResponse`
 */
public object GetBookmarkCollectionsEntryResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bookmark_collections_entries.BookmarkCollectionEntries.GetBookmarkCollectionsEntryResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bookmark_collections_entries.BookmarkCollectionEntries.GetBookmarkCollectionsEntryResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bookmark_collections_entries.BookmarkCollectionEntries.GetBookmarkCollectionsEntryResponse = _builder.build()

    /**
     * `string title = 1;`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.title
      @JvmName("setTitle")
      set(value) {
        _builder.title = value
      }
    /**
     * `string title = 1;`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * `string description = 2;`
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.description
      @JvmName("setDescription")
      set(value) {
        _builder.description = value
      }
    /**
     * `string description = 2;`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * `string created_at = 3;`
     */
    public var createdAt: kotlin.String
      @JvmName("getCreatedAt")
      get() = _builder.createdAt
      @JvmName("setCreatedAt")
      set(value) {
        _builder.createdAt = value
      }
    /**
     * `string created_at = 3;`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }

    /**
     * `string updated_at = 4;`
     */
    public var updatedAt: kotlin.String
      @JvmName("getUpdatedAt")
      get() = _builder.updatedAt
      @JvmName("setUpdatedAt")
      set(value) {
        _builder.updatedAt = value
      }
    /**
     * `string updated_at = 4;`
     */
    public fun clearUpdatedAt() {
      _builder.clearUpdatedAt()
    }

    /**
     * `string collection_id = 5;`
     */
    public var collectionId: kotlin.String
      @JvmName("getCollectionId")
      get() = _builder.collectionId
      @JvmName("setCollectionId")
      set(value) {
        _builder.collectionId = value
      }
    /**
     * `string collection_id = 5;`
     */
    public fun clearCollectionId() {
      _builder.clearCollectionId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MoreFieldsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `map<string, string> more_fields = 6;`
     */
     public val moreFields: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MoreFieldsProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getMoreFieldsMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.moreFieldsMap
      )
    /**
     * `map<string, string> more_fields = 6;`
     */
    @JvmName("putMoreFields")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MoreFieldsProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putMoreFields(key, value)
       }
    /**
     * `map<string, string> more_fields = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setMoreFields")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MoreFieldsProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * `map<string, string> more_fields = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeMoreFields")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MoreFieldsProxy>
      .remove(key: kotlin.String) {
         _builder.removeMoreFields(key)
       }
    /**
     * `map<string, string> more_fields = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllMoreFields")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MoreFieldsProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllMoreFields(map)
       }
    /**
     * `map<string, string> more_fields = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearMoreFields")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MoreFieldsProxy>
      .clear() {
         _builder.clearMoreFields()
       }

    /**
     * `string entry_id = 8;`
     */
    public var entryId: kotlin.String
      @JvmName("getEntryId")
      get() = _builder.entryId
      @JvmName("setEntryId")
      set(value) {
        _builder.entryId = value
      }
    /**
     * `string entry_id = 8;`
     */
    public fun clearEntryId() {
      _builder.clearEntryId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bookmark_collections_entries.BookmarkCollectionEntries.GetBookmarkCollectionsEntryResponse.copy(block: `bookmark_collections_entries`.GetBookmarkCollectionsEntryResponseKt.Dsl.() -> kotlin.Unit): bookmark_collections_entries.BookmarkCollectionEntries.GetBookmarkCollectionsEntryResponse =
  `bookmark_collections_entries`.GetBookmarkCollectionsEntryResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

