// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bookmark_collection_entries.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bookmark_collections_entries;

@kotlin.jvm.JvmName("-initializeupdateBookmarkCollectionsEntryRequest")
public inline fun updateBookmarkCollectionsEntryRequest(block: bookmark_collections_entries.UpdateBookmarkCollectionsEntryRequestKt.Dsl.() -> kotlin.Unit): bookmark_collections_entries.BookmarkCollectionEntries.UpdateBookmarkCollectionsEntryRequest =
  bookmark_collections_entries.UpdateBookmarkCollectionsEntryRequestKt.Dsl._create(bookmark_collections_entries.BookmarkCollectionEntries.UpdateBookmarkCollectionsEntryRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `bookmark_collections_entries.UpdateBookmarkCollectionsEntryRequest`
 */
public object UpdateBookmarkCollectionsEntryRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bookmark_collections_entries.BookmarkCollectionEntries.UpdateBookmarkCollectionsEntryRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bookmark_collections_entries.BookmarkCollectionEntries.UpdateBookmarkCollectionsEntryRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bookmark_collections_entries.BookmarkCollectionEntries.UpdateBookmarkCollectionsEntryRequest = _builder.build()

    /**
     * `string collection_id = 1;`
     */
    public var collectionId: kotlin.String
      @JvmName("getCollectionId")
      get() = _builder.collectionId
      @JvmName("setCollectionId")
      set(value) {
        _builder.collectionId = value
      }
    /**
     * `string collection_id = 1;`
     */
    public fun clearCollectionId() {
      _builder.clearCollectionId()
    }

    /**
     * `optional string title = 2;`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.title
      @JvmName("setTitle")
      set(value) {
        _builder.title = value
      }
    /**
     * `optional string title = 2;`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }
    /**
     * `optional string title = 2;`
     * @return Whether the title field is set.
     */
    public fun hasTitle(): kotlin.Boolean {
      return _builder.hasTitle()
    }

    /**
     * `optional string description = 3;`
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.description
      @JvmName("setDescription")
      set(value) {
        _builder.description = value
      }
    /**
     * `optional string description = 3;`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }
    /**
     * `optional string description = 3;`
     * @return Whether the description field is set.
     */
    public fun hasDescription(): kotlin.Boolean {
      return _builder.hasDescription()
    }

    /**
     * `string entry_id = 4;`
     */
    public var entryId: kotlin.String
      @JvmName("getEntryId")
      get() = _builder.entryId
      @JvmName("setEntryId")
      set(value) {
        _builder.entryId = value
      }
    /**
     * `string entry_id = 4;`
     */
    public fun clearEntryId() {
      _builder.clearEntryId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bookmark_collections_entries.BookmarkCollectionEntries.UpdateBookmarkCollectionsEntryRequest.copy(block: `bookmark_collections_entries`.UpdateBookmarkCollectionsEntryRequestKt.Dsl.() -> kotlin.Unit): bookmark_collections_entries.BookmarkCollectionEntries.UpdateBookmarkCollectionsEntryRequest =
  `bookmark_collections_entries`.UpdateBookmarkCollectionsEntryRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

