# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_profile.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'user_profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_profile.proto\x12\x0cuser_profile\"\x10\n\x0eProfileRequest\"S\n\x0fProfileResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"\x82\x01\n\x14ProfileUpdateRequest\x12\x16\n\tlast_name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nfirst_name\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05\x65mail\x18\x04 \x01(\tH\x02\x88\x01\x01\x42\x0c\n\n_last_nameB\r\n\x0b_first_nameB\x08\n\x06_email\"Y\n\x15ProfileUpdateResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t2\xb2\x01\n\x0bUserProfile\x12I\n\nGetProfile\x12\x1c.user_profile.ProfileRequest\x1a\x1d.user_profile.ProfileResponse\x12X\n\rUpdateProfile\x12\".user_profile.ProfileUpdateRequest\x1a#.user_profile.ProfileUpdateResponseB%Z#bookmarks/grpc/codegen/user_profileb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#bookmarks/grpc/codegen/user_profile'
  _globals['_PROFILEREQUEST']._serialized_start=36
  _globals['_PROFILEREQUEST']._serialized_end=52
  _globals['_PROFILERESPONSE']._serialized_start=54
  _globals['_PROFILERESPONSE']._serialized_end=137
  _globals['_PROFILEUPDATEREQUEST']._serialized_start=140
  _globals['_PROFILEUPDATEREQUEST']._serialized_end=270
  _globals['_PROFILEUPDATERESPONSE']._serialized_start=272
  _globals['_PROFILEUPDATERESPONSE']._serialized_end=361
  _globals['_USERPROFILE']._serialized_start=364
  _globals['_USERPROFILE']._serialized_end=542
# @@protoc_insertion_point(module_scope)
