// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: activity.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package activity_log;

@kotlin.jvm.JvmName("-initializelogActivityRequest")
public inline fun logActivityRequest(block: activity_log.LogActivityRequestKt.Dsl.() -> kotlin.Unit): activity_log.Activity.LogActivityRequest =
  activity_log.LogActivityRequestKt.Dsl._create(activity_log.Activity.LogActivityRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `activity_log.LogActivityRequest`
 */
public object LogActivityRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: activity_log.Activity.LogActivityRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: activity_log.Activity.LogActivityRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): activity_log.Activity.LogActivityRequest = _builder.build()

    /**
     * `string location = 1;`
     */
    public var location: kotlin.String
      @JvmName("getLocation")
      get() = _builder.location
      @JvmName("setLocation")
      set(value) {
        _builder.location = value
      }
    /**
     * `string location = 1;`
     */
    public fun clearLocation() {
      _builder.clearLocation()
    }

    /**
     * `string time = 2;`
     */
    public var time: kotlin.String
      @JvmName("getTime")
      get() = _builder.time
      @JvmName("setTime")
      set(value) {
        _builder.time = value
      }
    /**
     * `string time = 2;`
     */
    public fun clearTime() {
      _builder.clearTime()
    }

    /**
     * `string date = 3;`
     */
    public var date: kotlin.String
      @JvmName("getDate")
      get() = _builder.date
      @JvmName("setDate")
      set(value) {
        _builder.date = value
      }
    /**
     * `string date = 3;`
     */
    public fun clearDate() {
      _builder.clearDate()
    }

    /**
     * `string os = 4;`
     */
    public var os: kotlin.String
      @JvmName("getOs")
      get() = _builder.os
      @JvmName("setOs")
      set(value) {
        _builder.os = value
      }
    /**
     * `string os = 4;`
     */
    public fun clearOs() {
      _builder.clearOs()
    }

    /**
     * `string action = 5;`
     */
    public var action: kotlin.String
      @JvmName("getAction")
      get() = _builder.action
      @JvmName("setAction")
      set(value) {
        _builder.action = value
      }
    /**
     * `string action = 5;`
     */
    public fun clearAction() {
      _builder.clearAction()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun activity_log.Activity.LogActivityRequest.copy(block: `activity_log`.LogActivityRequestKt.Dsl.() -> kotlin.Unit): activity_log.Activity.LogActivityRequest =
  `activity_log`.LogActivityRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

