/**
 * @fileoverview gRPC-Web generated client stub for activity_log
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.26.1
// source: proto/activity.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_activity_pb from '../proto/activity_pb'; // proto import: "proto/activity.proto"


export class ActivityLogClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorLogActivity = new grpcWeb.MethodDescriptor(
    '/activity_log.ActivityLog/LogActivity',
    grpcWeb.MethodType.UNARY,
    proto_activity_pb.LogActivityRequest,
    proto_activity_pb.LogActivityResponse,
    (request: proto_activity_pb.LogActivityRequest) => {
      return request.serializeBinary();
    },
    proto_activity_pb.LogActivityResponse.deserializeBinary
  );

  logActivity(
    request: proto_activity_pb.LogActivityRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_activity_pb.LogActivityResponse>;

  logActivity(
    request: proto_activity_pb.LogActivityRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_activity_pb.LogActivityResponse) => void): grpcWeb.ClientReadableStream<proto_activity_pb.LogActivityResponse>;

  logActivity(
    request: proto_activity_pb.LogActivityRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_activity_pb.LogActivityResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/activity_log.ActivityLog/LogActivity',
        request,
        metadata || {},
        this.methodDescriptorLogActivity,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/activity_log.ActivityLog/LogActivity',
    request,
    metadata || {},
    this.methodDescriptorLogActivity);
  }

}

