// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package common;

@kotlin.jvm.JvmName("-initializeerrorResponse")
public inline fun errorResponse(block: common.ErrorResponseKt.Dsl.() -> kotlin.Unit): common.Common.ErrorResponse =
  common.ErrorResponseKt.Dsl._create(common.Common.ErrorResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `common.ErrorResponse`
 */
public object ErrorResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: common.Common.ErrorResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: common.Common.ErrorResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): common.Common.ErrorResponse = _builder.build()

    /**
     * `int32 code = 1;`
     */
    public var code: kotlin.Int
      @JvmName("getCode")
      get() = _builder.code
      @JvmName("setCode")
      set(value) {
        _builder.code = value
      }
    /**
     * `int32 code = 1;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * `string message = 2;`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.message
      @JvmName("setMessage")
      set(value) {
        _builder.message = value
      }
    /**
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun common.Common.ErrorResponse.copy(block: `common`.ErrorResponseKt.Dsl.() -> kotlin.Unit): common.Common.ErrorResponse =
  `common`.ErrorResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

