// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authentication.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package authentication;

@kotlin.jvm.JvmName("-initializeloginRequest")
public inline fun loginRequest(block: authentication.LoginRequestKt.Dsl.() -> kotlin.Unit): authentication.AuthenticationOuterClass.LoginRequest =
  authentication.LoginRequestKt.Dsl._create(authentication.AuthenticationOuterClass.LoginRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `authentication.LoginRequest`
 */
public object LoginRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: authentication.AuthenticationOuterClass.LoginRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: authentication.AuthenticationOuterClass.LoginRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): authentication.AuthenticationOuterClass.LoginRequest = _builder.build()

    /**
     * `string email = 1;`
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.email
      @JvmName("setEmail")
      set(value) {
        _builder.email = value
      }
    /**
     * `string email = 1;`
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }

    /**
     * `string password = 2;`
     */
    public var password: kotlin.String
      @JvmName("getPassword")
      get() = _builder.password
      @JvmName("setPassword")
      set(value) {
        _builder.password = value
      }
    /**
     * `string password = 2;`
     */
    public fun clearPassword() {
      _builder.clearPassword()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun authentication.AuthenticationOuterClass.LoginRequest.copy(block: `authentication`.LoginRequestKt.Dsl.() -> kotlin.Unit): authentication.AuthenticationOuterClass.LoginRequest =
  `authentication`.LoginRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

