// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authentication.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package authentication;

@kotlin.jvm.JvmName("-initializesetNewPasswordResponse")
public inline fun setNewPasswordResponse(block: authentication.SetNewPasswordResponseKt.Dsl.() -> kotlin.Unit): authentication.AuthenticationOuterClass.SetNewPasswordResponse =
  authentication.SetNewPasswordResponseKt.Dsl._create(authentication.AuthenticationOuterClass.SetNewPasswordResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `authentication.SetNewPasswordResponse`
 */
public object SetNewPasswordResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: authentication.AuthenticationOuterClass.SetNewPasswordResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: authentication.AuthenticationOuterClass.SetNewPasswordResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): authentication.AuthenticationOuterClass.SetNewPasswordResponse = _builder.build()

    /**
     * `.authentication.Status status = 1;`
     */
    public var status: authentication.AuthenticationOuterClass.Status
      @JvmName("getStatus")
      get() = _builder.status
      @JvmName("setStatus")
      set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.statusValue
      @JvmName("setStatusValue")
      set(value) {
        _builder.statusValue = value
      }
    /**
     * `.authentication.Status status = 1;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `string message = 2;`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.message
      @JvmName("setMessage")
      set(value) {
        _builder.message = value
      }
    /**
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun authentication.AuthenticationOuterClass.SetNewPasswordResponse.copy(block: `authentication`.SetNewPasswordResponseKt.Dsl.() -> kotlin.Unit): authentication.AuthenticationOuterClass.SetNewPasswordResponse =
  `authentication`.SetNewPasswordResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

