// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeleteVaultEntryResponse = { vault_id: string, vault_entry_id: string, status: string, };
