// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VaultEntries } from "./VaultEntries";

export type ListVaultEntryResponse = { vault_entries: Array<VaultEntries>, total_count: number, };
