// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewBookmarkCollectionsEntryRequest = { title: string, description: string, bookmark_collection_id: string, more_fields: { [key in string]?: string }, };
