// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileUpdateRequest = { last_name: string | null, first_name: string | null, email: string | null, };
