// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateVaultEntryRequest = { vault_id: string, title: string | null, description: string | null, vault_entry_id: string, };
