// This file is @generated by prost-build.
#[derive(serde::Deserialize, ts_rs::TS, serde::Serialize)]
#[ts(export)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BookmarkCollectionEntries {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub updated_at: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub bookmark_collection_id: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "6")]
    pub more_fields: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(serde::Deserialize, ts_rs::TS, serde::Serialize)]
#[ts(export)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewBookmarkCollectionRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
}
#[derive(serde::Deserialize, ts_rs::TS, serde::Serialize)]
#[ts(export)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewBookmarkCollectionResponse {
    #[prost(string, tag = "1")]
    pub bookmark_collection_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub updated_at: ::prost::alloc::string::String,
}
#[derive(serde::Deserialize, ts_rs::TS, serde::Serialize)]
#[ts(export)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBookmarkCollectionRequest {
    #[prost(string, tag = "1")]
    pub bookmark_collection_id: ::prost::alloc::string::String,
}
#[derive(serde::Deserialize, ts_rs::TS, serde::Serialize)]
#[ts(export)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBookmarkCollectionResponse {
    #[prost(string, tag = "1")]
    pub bookmark_collection_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub updated_at: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "7")]
    pub entries: ::prost::alloc::vec::Vec<BookmarkCollectionEntries>,
}
#[derive(serde::Deserialize, ts_rs::TS, serde::Serialize)]
#[ts(export)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateBookmarkCollectionRequest {
    #[prost(string, tag = "1")]
    pub bookmark_collection_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Deserialize, ts_rs::TS, serde::Serialize)]
#[ts(export)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateBookmarkCollectionResponse {
    #[prost(string, tag = "1")]
    pub bookmark_collection_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
}
#[derive(serde::Deserialize, ts_rs::TS, serde::Serialize)]
#[ts(export)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteBookmarkCollectionRequest {
    #[prost(string, tag = "1")]
    pub bookmark_collection_id: ::prost::alloc::string::String,
}
#[derive(serde::Deserialize, ts_rs::TS, serde::Serialize)]
#[ts(export)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteBookmarkCollectionResponse {
    #[prost(string, tag = "1")]
    pub bookmark_collection_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(serde::Deserialize, ts_rs::TS, serde::Serialize)]
#[ts(export)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListBookmarkCollectionsRequest {
    #[prost(uint32, tag = "1")]
    pub page: u32,
    #[prost(uint32, tag = "2")]
    pub page_size: u32,
}
#[derive(serde::Deserialize, ts_rs::TS, serde::Serialize)]
#[ts(export)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BookmarkCollection {
    #[prost(string, tag = "1")]
    pub bookmark_collection_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub updated_at: ::prost::alloc::string::String,
}
#[derive(serde::Deserialize, ts_rs::TS, serde::Serialize)]
#[ts(export)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListBookmarkCollectionsResponse {
    #[prost(message, repeated, tag = "1")]
    pub bookmark_collections: ::prost::alloc::vec::Vec<BookmarkCollection>,
    #[prost(uint32, tag = "2")]
    pub total_count: u32,
}
#[derive(serde::Deserialize, ts_rs::TS, serde::Serialize)]
#[ts(export)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListBookmarkCollectionEntryRequest {
    #[prost(string, tag = "1")]
    pub bookmark_collection_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub page: u32,
    #[prost(uint32, tag = "5")]
    pub page_size: u32,
}
#[derive(serde::Deserialize, ts_rs::TS, serde::Serialize)]
#[ts(export)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListBookmarkCollectionEntryResponse {
    #[prost(message, repeated, tag = "1")]
    pub bookmark_collection_entries: ::prost::alloc::vec::Vec<BookmarkCollectionEntries>,
    #[prost(uint32, tag = "2")]
    pub total_count: u32,
}
/// Generated client implementations.
pub mod bookmark_collection_manager_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct BookmarkCollectionManagerClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl BookmarkCollectionManagerClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> BookmarkCollectionManagerClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> BookmarkCollectionManagerClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            BookmarkCollectionManagerClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn create_new_bookmark_collection(
            &mut self,
            request: impl tonic::IntoRequest<super::NewBookmarkCollectionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::NewBookmarkCollectionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/BookmarkCollection.BookmarkCollectionManager/CreateNewBookmarkCollection",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "BookmarkCollection.BookmarkCollectionManager",
                        "CreateNewBookmarkCollection",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_bookmark_collection(
            &mut self,
            request: impl tonic::IntoRequest<super::GetBookmarkCollectionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBookmarkCollectionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/BookmarkCollection.BookmarkCollectionManager/GetBookmarkCollection",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "BookmarkCollection.BookmarkCollectionManager",
                        "GetBookmarkCollection",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_bookmark_collection(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateBookmarkCollectionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBookmarkCollectionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/BookmarkCollection.BookmarkCollectionManager/UpdateBookmarkCollection",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "BookmarkCollection.BookmarkCollectionManager",
                        "UpdateBookmarkCollection",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_bookmark_collection(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteBookmarkCollectionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteBookmarkCollectionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/BookmarkCollection.BookmarkCollectionManager/DeleteBookmarkCollection",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "BookmarkCollection.BookmarkCollectionManager",
                        "DeleteBookmarkCollection",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_bookmark_collections(
            &mut self,
            request: impl tonic::IntoRequest<super::ListBookmarkCollectionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListBookmarkCollectionsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/BookmarkCollection.BookmarkCollectionManager/ListBookmarkCollections",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "BookmarkCollection.BookmarkCollectionManager",
                        "ListBookmarkCollections",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_bookmark_collection_entries(
            &mut self,
            request: impl tonic::IntoRequest<super::ListBookmarkCollectionEntryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListBookmarkCollectionEntryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/BookmarkCollection.BookmarkCollectionManager/ListBookmarkCollectionEntries",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "BookmarkCollection.BookmarkCollectionManager",
                        "ListBookmarkCollectionEntries",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
